name: MineStormRBW
version: 1.0.0
main: com.minestorm.rbw.MineStormRBW.main
author: Muvixo
api-version: 1.8
depend: [ProtocolLib]
commands:
  reloadhit:
    description: Reloads the MineStormRBW config
